name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Migrations
        env:
          MONGO_URI: mongodb+srv://salimraji:1234@mycluster.lbrtq.mongodb.net/?retryWrites=true&w=majority&appName=myCluster
        run: |
          npx migrate-mongo up
      
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/v1/deploys \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{"serviceId": "srv-cs7q8ulumphs73absl00"}'
